name: main
run-name: main
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      profile:
        required: true
        type: string
      preset-configure:
        required: true
        type: string
      preset-build:
        required: true
        type: string
jobs:
  build-main:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true
      - name: Checkout Skia recipe
        uses: actions/checkout@v4
        with:
          repository: 'mocabe/conan-skia'
          path: 'conan-skia'
      - name: Add Skia recipe to Conan
        run: conan remote add conan_skia ./conan-skia
      - name: Install dependencies
        run:  conan install -pr:b=default -pr:h=${{ inputs.profile }} --build=missing
      - name: Configure
        run: cmake --preset ${{ inputs.preset-configure }}
      - name: Build
        run: cmake --build --preset ${{ inputs.preset-build }}
