name: windows
run-name: windows
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      runs-on: windows-latest
      profile: ./profile/windows_x86_64_Debug.profile
      preset-configure: conan-default
      preset-build: conan-debug
